export const vendorsCatalog = {
  name: "Vendors (Supplier)",
  paths: ["logistik/master/vendors"],
  items: [
    {
      id: "ven-001",
      nama: "CV YODERINDO INTI PRIMA",
      nama_perusahaan: "CV YODERINDO INTI PRIMA",
      pimpinan: "YOSIA MASLIPUTRA",
      jabatan: "Direktur",
      alamat: "Jl. Beringin Blok B No.1 Rt01/004 Kedung Halang, Bogor Utara",
      kota: "BOGOR",
      no_telp: "083811106700",
      kontak: "083811106700",
      keterangan: "CCTV",
    },
    {
      id: "ven-002",
      nama: "PT DANAKAR",
      nama_perusahaan: "PT DANAKAR",
      pimpinan: "HUSEIN IZZATI",
      jabatan: "Direktur",
      alamat: "Jl. Otista Raya No. 68A, Bidara Cina, Jatinegara",
      kota: "JAKARTA",
      no_telp: "081297220944",
      kontak: "081297220944",
      keterangan: "BANGUNAN",
    },
    {
      id: "ven-003",
      nama: "PT IMTEK TRIVISHAKA HADITAMA",
      nama_perusahaan: "PT IMTEK TRIVISHAKA HADITAMA",
      pimpinan: "IMAM SUHADI",
      jabatan: "Direktur",
      alamat: "Ruko Symphoni Blok HX 1, No. 22 Harapan Indah Bekasi",
      kota: "BEKASI",
      no_telp: "083845078652",
      kontak: "083845078652",
      keterangan: "LIFT",
    },
    {
      id: "ven-004",
      nama: "PT JAYA MULTI DIMENSI",
      nama_perusahaan: "PT JAYA MULTI DIMENSI",
      pimpinan: "RATNO NUGROHO",
      jabatan: "Direktur",
      alamat: "Ruko Maisonette Blok B/21 Jl. Percetakan Negara II Kel. Johar Baru, Kec. Johar Baru",
      kota: "JAKARTA",
      no_telp: "081289260604",
      kontak: "081289260604",
      keterangan: "BANGUNAN",
    },
    {
      id: "ven-005",
      nama: "PT ERA PERMATA SEJAHTERA",
      nama_perusahaan: "PT ERA PERMATA SEJAHTERA",
      pimpinan: "WIDI HARTANTA",
      jabatan: "Direktur",
      alamat: "Jl. Cipinang Jaya Raya AA/9 Cipinang Muara",
      kota: "JAKARTA",
      no_telp: "082112871756",
      kontak: "082112871756",
      keterangan: "BANGUNAN",
    },
  ],
};
